#pragma once
#include <Arduino.h>
#include <string.h>

// TFLite Micro — built into ESP32 core 3.3.7 (espressif__esp-tflite-micro)
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "cnn_model.h"   // generated by train/train_cnn.py

// ── constants ─────────────────────────────────────────────────────
#define FLOW_FAST    1
#define FLOW_NORMAL  0
#define FLOW_SLOW   -1

#define CNN_DIM  8
#define CNN_WIN  (CNN_DIM * CNN_DIM)   // 64-sample rolling window

#define TENSOR_ARENA_KB  16
#define TENSOR_ARENA_SZ  (TENSOR_ARENA_KB * 1024)

// 단일 샘플 허용 오차: ±30%
#define DEFAULT_TOLERANCE    0.30f
// CNN 결과 신뢰도 임계값: 이 이상일 때만 결과 반영
#define DEFAULT_CNN_THRESH   0.75f
// Fallback: fast/slow 픽셀 비율이 이 이상이면 이상 판정
#define DEFAULT_RATIO_THRESH 0.40f

/*
 * CNNDetector — 3클래스 분류 (SLOW / NORMAL / FAST)
 *
 * CNN 출력: [P(slow), P(normal), P(fast)]  → argmax로 상태 결정
 * Fallback: 이미지 내 +1/-1 픽셀 비율로 판단
 *
 * 64샘플(= 64초) 쌓인 후부터 getWindowResult() 유효
 */
class CNNDetector {
public:
  CNNDetector()
    : _head(0), _count(0), _lastState(FLOW_NORMAL),
      _windowResult(FLOW_NORMAL), _windowConfidence(0.0f),
      _hasResult(false), _alertPending(false),
      _tolerance(DEFAULT_TOLERANCE),
      _cnnThresh(DEFAULT_CNN_THRESH),
      _ratioThresh(DEFAULT_RATIO_THRESH),
      _model(nullptr), _interpreter(nullptr),
      _tfliteReady(false), _useFallback(false)
  {
    memset(_buf,   0, sizeof(_buf));
    memset(_image, 0, sizeof(_image));
    memset(_arena, 0, sizeof(_arena));
  }

  bool begin() {
#ifndef CNN_MODEL_AVAILABLE
    Serial.println("[CNN] Placeholder model — fallback mode.");
    Serial.println("[CNN] Run train/train_cnn.py then recompile.");
    _useFallback = true;
    return false;
#else
    _model = tflite::GetModel(cnn_model_data);
    if (_model->version() != TFLITE_SCHEMA_VERSION) {
      Serial.printf("[CNN] Schema mismatch: model=%u, lib=%u\n",
                    _model->version(), TFLITE_SCHEMA_VERSION);
      _useFallback = true;
      return false;
    }

    static tflite::MicroMutableOpResolver<5> resolver;
    static bool resolverReady = false;
    if (!resolverReady) {
      resolver.AddConv2D();
      resolver.AddMaxPool2D();
      resolver.AddReshape();
      resolver.AddFullyConnected();
      resolver.AddSoftmax();
      resolverReady = true;
    }

    _interpreter = new tflite::MicroInterpreter(
      _model, resolver, _arena, TENSOR_ARENA_SZ
    );

    if (_interpreter->AllocateTensors() != kTfLiteOk) {
      Serial.println("[CNN] AllocateTensors failed — increase TENSOR_ARENA_KB.");
      _useFallback = true;
      return false;
    }

    Serial.printf("[CNN] TFLite ready. Arena used: %u / %u bytes\n",
                  (unsigned)_interpreter->arena_used_bytes(), TENSOR_ARENA_SZ);

    TfLiteTensor *in  = _interpreter->input(0);
    TfLiteTensor *out = _interpreter->output(0);
    bool shapeOK = (in->dims->size == 4)
                && (in->dims->data[1] == CNN_DIM)
                && (in->dims->data[2] == CNN_DIM)
                && (in->dims->data[3] == 1)
                && (out->dims->data[1] == 3);   // 3클래스
    if (!shapeOK) {
      Serial.println("[CNN] Tensor shape mismatch — check model.");
      _useFallback = true;
      return false;
    }

    _tfliteReady = true;
    return true;
#endif
  }

  // ── 샘플 추가 ─────────────────────────────────────────────────────
  void setTolerance(float t)   { _tolerance  = t; }
  void setCNNThresh(float t)   { _cnnThresh  = t; }
  void setRatioThresh(float t) { _ratioThresh = t; }

  void addSample(float measured, float target) {
    _lastState      = encodeState(measured, target);
    _buf[_head]     = _lastState;
    _head           = (_head + 1) % CNN_WIN;
    _count++;

    // 64개 채워지면 CNN 실행 후 버퍼 초기화
    // 다음 샘플은 새 윈도우의 1번째가 됨
    if (_count >= CNN_WIN) {
      buildImage();
      runClassify();
      _hasResult = true;
      // 이상 감지 시 1회 알림 플래그 세트
      if (_windowResult != FLOW_NORMAL) _alertPending = true;
      // 버퍼 초기화 — 다음 64샘플을 새로 수집
      memset(_buf, 0, sizeof(_buf));
      _head  = 0;
      _count = 0;
    }
  }

  int encodeState(float measured, float target) {
    if (target <= 0) return FLOW_NORMAL;
    float ratio = (measured - target) / target;
    if (ratio >  _tolerance) return FLOW_FAST;
    if (ratio < -_tolerance) return FLOW_SLOW;
    return FLOW_NORMAL;
  }

  // ── 결과 조회 ─────────────────────────────────────────────────────

  // 64샘플 윈도우 전체 분류 결과: FLOW_SLOW / FLOW_NORMAL / FLOW_FAST
  int   getWindowResult()     const { return _windowResult; }
  // 해당 결과의 신뢰도 (0.0 ~ 1.0)
  float getWindowConfidence() const { return _windowConfidence; }
  // 결과가 유효한가 (첫 번째 윈도우가 완성됐는가)
  bool  isWindowFull()        const { return _hasResult; }
  // 현재 윈도우에서 수집된 샘플 수 (0~63)
  int   getSampleCount()      const { return _count; }
  // 이상 감지 여부 — 윈도우 완성 직후 1회만 true, 이후 자동 클리어
  bool detectAnomaly() {
    if (_alertPending) { _alertPending = false; return true; }
    return false;
  }

  // 단일 샘플 상태 (매 측정마다 갱신)
  int   getLastState()        const { return _lastState; }
  bool  isTFLiteActive()      const { return _tfliteReady; }

  // 결과를 한국어 문자열로
  const char* getResultLabel() const {
    if (!isWindowFull()) return "수집중";
    switch (_windowResult) {
      case FLOW_FAST:   return "유속 빠름";
      case FLOW_SLOW:   return "유속 느림";
      default:          return "정상";
    }
  }

  void getImage(int out[CNN_DIM][CNN_DIM]) {
    memcpy(out, _image, sizeof(_image));
  }

  void reset() {
    memset(_buf,   0, sizeof(_buf));
    memset(_image, 0, sizeof(_image));
    _head = 0; _count = 0;
    _lastState        = FLOW_NORMAL;
    _windowResult     = FLOW_NORMAL;
    _windowConfidence = 0.0f;
    _hasResult        = false;
    _alertPending     = false;
  }

private:
  int   _buf[CNN_WIN];
  int   _image[CNN_DIM][CNN_DIM];
  int   _head, _count, _lastState;
  int   _windowResult;
  float _windowConfidence;
  bool  _hasResult, _alertPending;

  float _tolerance, _cnnThresh, _ratioThresh;

  const tflite::Model      *_model;
  tflite::MicroInterpreter *_interpreter;
  alignas(16) uint8_t       _arena[TENSOR_ARENA_SZ];
  bool _tfliteReady, _useFallback;

  void buildImage() {
    for (int r = 0; r < CNN_DIM; r++)
      for (int c = 0; c < CNN_DIM; c++)
        _image[r][c] = _buf[(_head + r * CNN_DIM + c) % CNN_WIN];
  }

  // 추론 실행 → _windowResult, _windowConfidence 갱신
  void runClassify() {
    if (_tfliteReady) {
      classifyCNN();
    } else {
      classifyFallback();
    }
  }

  void classifyCNN() {
#ifdef CNN_MODEL_AVAILABLE
    TfLiteTensor *input = _interpreter->input(0);
    for (int r = 0; r < CNN_DIM; r++)
      for (int c = 0; c < CNN_DIM; c++)
        input->data.f[r * CNN_DIM + c] = (float)_image[r][c];

    if (_interpreter->Invoke() != kTfLiteOk) {
      Serial.println("[CNN] Invoke failed — fallback.");
      classifyFallback();
      return;
    }

    // output: [P(slow), P(normal), P(fast)]
    float pSlow   = _interpreter->output(0)->data.f[0];
    float pNormal = _interpreter->output(0)->data.f[1];
    float pFast   = _interpreter->output(0)->data.f[2];

    if (pNormal >= _cnnThresh) {
      _windowResult     = FLOW_NORMAL;
      _windowConfidence = pNormal;
    } else if (pFast > pSlow) {
      _windowResult     = FLOW_FAST;
      _windowConfidence = pFast;
    } else {
      _windowResult     = FLOW_SLOW;
      _windowConfidence = pSlow;
    }
#endif
  }

  // Fallback: +1/-1 픽셀 비율로 판단
  void classifyFallback() {
    int fast = 0, slow = 0;
    for (int r = 0; r < CNN_DIM; r++)
      for (int c = 0; c < CNN_DIM; c++) {
        if (_image[r][c] == FLOW_FAST) fast++;
        if (_image[r][c] == FLOW_SLOW) slow++;
      }
    float ratioFast = (float)fast / CNN_WIN;
    float ratioSlow = (float)slow / CNN_WIN;

    if (ratioFast >= _ratioThresh && ratioFast > ratioSlow) {
      _windowResult     = FLOW_FAST;
      _windowConfidence = ratioFast;
    } else if (ratioSlow >= _ratioThresh && ratioSlow > ratioFast) {
      _windowResult     = FLOW_SLOW;
      _windowConfidence = ratioSlow;
    } else {
      _windowResult     = FLOW_NORMAL;
      _windowConfidence = 1.0f - max(ratioFast, ratioSlow);
    }
  }
};
